# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 100 Coisas Dev
email: leonardo.balter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Quais são as 100 coisas em desenvolvimento que você vai fazer em 2016?
baseurl: "/100-coisas-dev" # the subpath of your site, e.g. /blog
url: "http://leobalter.github.io" # the base hostname & protocol for your site
twitter_username: leobalter
github_username:  leobalter
permalink: /:categories/:title/
comments: true

# Build settings
markdown: kramdown
